#!/usr/bin/env ruby

# ======================================================
# = Replace address in pts_and_ags_nov_5_concated.json =
# ======================================================

input_file  = './pts_and_ags_nov_5_concated.json'
output_file = './pts_and_ags_nov_5_concated_replaced.json'
# substituions are verified and generated by verify_message.rb
replacements =<<EOF
1Gaw39RvbkZxcXeYzGrjWvmiEqAB6PMqsX => 1A2SAL7i5UwZ3pYuaf7rcBj1U3wffEAoo7
13U3XLUTRHLGMwfCmhde7EmQtNdJE7X2zw => 1A2SAL7i5UwZ3pYuaf7rcBj1U3wffEAoo7
178RVtWSyrCD8N1BnSdiSbMMokD2foQhAd => 1KfjASdNiX97R8eJM9HPbnKcFWZ8RRhzzb
1GJczjbQF8evXsLCHpX9sNXQ3m2QbwH2Wv => 1KfjASdNiX97R8eJM9HPbnKcFWZ8RRhzzb
19btdFcvEgF6t7hyr5n4gzsGitHZjk7uF4 => 1KfjASdNiX97R8eJM9HPbnKcFWZ8RRhzzb
1J9FPXTMJXwh1mC4CYDp8kjtgsQehiVos4 => 1KfjASdNiX97R8eJM9HPbnKcFWZ8RRhzzb
18Cpgt8w1aFsGBc3s82NMCU5RiRE1kiEe3 => 1KfjASdNiX97R8eJM9HPbnKcFWZ8RRhzzb
1MnEmUHF9TYXMio86dTGXvRxeirW4VFE9w => 1KfjASdNiX97R8eJM9HPbnKcFWZ8RRhzzb
1DL9Rt8bWZbmNbSMZedqA2WeFRUeJS415s => 1KfjASdNiX97R8eJM9HPbnKcFWZ8RRhzzb
1QC9jKo53vAdo6zYUcHwpJWqGwCe5voxLv => 1KfjASdNiX97R8eJM9HPbnKcFWZ8RRhzzb
1JtuJEr3cGL7AyB4xcg9qMLjWV73qnHRBt => 1KfjASdNiX97R8eJM9HPbnKcFWZ8RRhzzb
1G3HMZzCr4QDihJEpz1arrmR4swm7krinM => 1KfjASdNiX97R8eJM9HPbnKcFWZ8RRhzzb
1HziNRPCtiY6HXsBouwpVzTYtZws5A25LZ => 1KfjASdNiX97R8eJM9HPbnKcFWZ8RRhzzb
135xcKg36YPGi2c1yDuacgDJuxqWcporDv => 1KfjASdNiX97R8eJM9HPbnKcFWZ8RRhzzb
15MeKFbkdHp7357Ez3p1jnNdGSovoBKop6 => 1KfjASdNiX97R8eJM9HPbnKcFWZ8RRhzzb
12tiMQ2eFAsG5SwG1xYaejigbsXiqac6hx => 1KfjASdNiX97R8eJM9HPbnKcFWZ8RRhzzb
1GqU61rhQ6sbwLiTc4FYSNpKZyjEA827VV => 1KfjASdNiX97R8eJM9HPbnKcFWZ8RRhzzb
1ED1wLdA3WW7Xr3EPRhZH6LmWP7gwJP5Qj => 1KfjASdNiX97R8eJM9HPbnKcFWZ8RRhzzb
1PegsunSa7ThjbEoRHxxFa5M4BgfXjbAj1 => 1KfjASdNiX97R8eJM9HPbnKcFWZ8RRhzzb
14seLs1EwvsXTb3dLvchFgMquJnF2yJwd2 => 1KfjASdNiX97R8eJM9HPbnKcFWZ8RRhzzb
1NhBbVJJUPN7X451bN9FEEq4LxyWLSWcft => 1KfjASdNiX97R8eJM9HPbnKcFWZ8RRhzzb
12ZoxtSZVqApmRTmY75P6jYpYDLkPJzNai => 1KfjASdNiX97R8eJM9HPbnKcFWZ8RRhzzb
1NZHLx6jNqY3R3953j6oALgkkZF4VoM6rH => 1KfjASdNiX97R8eJM9HPbnKcFWZ8RRhzzb
14Efv8ZHhbFz1fJ3eD4tfKLyHVqAXMug7y => 1KfjASdNiX97R8eJM9HPbnKcFWZ8RRhzzb
12ahkRrYhBcRGT9GbGRc7Y8uMGe9WTLibF => 1KfjASdNiX97R8eJM9HPbnKcFWZ8RRhzzb
1TDLLyd684EqFHHwCuQuh5Hh1aEBZpEhv => 12Zv4sdQbm6bKpz5artZYoM8WbfFXKuTHC
16qGZVP5rgwQCeLSnf2U94dHBa3QMNHJ3F => 12Zv4sdQbm6bKpz5artZYoM8WbfFXKuTHC
1FnqQz36y18HK1EvaTCaGS65xUYDSTxBtx => 12Zv4sdQbm6bKpz5artZYoM8WbfFXKuTHC
1JyiMXW7NXjsyhp4hvsm77xFn3J4tvxuZa => 16fgrvY7ACrZDLNz9GWiwPfMuk34kZWKmf
1AEv2pKdGqJomxE9ApkW68QBg32QjjwA7b => 1BYrChoJn2UNMhTtWfRrqfcJ5ntkMYjTo8
1KgyqkYwq1uFMwc6MTeQKsz72jJfqHSBD9 => 1KLNYniYHM2UwYxSA7rjRtXqNFQEEUDhPv
1PUZQbeu94iarZtrkKXiL4ryAEsvcsEvcE => 13P4or5Dz8734Arqg2CQLXFtxy2DSjKdXa
1CbkZbefm25BYFeUUUQGEvt9HYWh39hvJk => 1M69AMjAkeKkk6YfuEECZzbz54EnXijzvk
13XnJ6zKd6qgK5Uu4zJw4bdPT8M7232ZBf => 1KfjASdNiX97R8eJM9HPbnKcFWZ8RRhzzb
1CRXTFk9AuPm3gVQAgZQZ3tWwn8CiZGqSR => 1D8Wr6cG2YTCaZL8oyRaUxogHnD3CJoS1D
PbXSuic9B1iEmgMiWqW93cdXFvPQsHXdUc => PfSQYEJYKN3YTmk74BwXy6fk2StTJczaQw
PitE7xxJvjzkVcs6BT5yRxV55YJqgFrhCU => PfSQYEJYKN3YTmk74BwXy6fk2StTJczaQw
EOF

# copy file
`cp #{input_file} #{output_file}`
# run replacement
replacements.split("\n").each do |line|
  old_addr, new_addr = line.split(/\s*=>\s*/)
  `sed 's/#{old_addr}/#{new_addr}/g' #{output_file} > tmp_file && mv tmp_file #{output_file}`
end
